application: speedy-now-88607
version: v1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:

handlers:
- url: /taskspr
  script: taskspr.app

- url: /getoption
  script: main.app

- url: /blobstore.*
  script: blobstore.app

- url: /getminutedata
  script: getminutedata.app

- url: /.*
  script: main.app
  
libraries:
- name: lxml
  version: "latest"
